// Design tokens exported as JavaScript objects for use in styled components
export const COLORS = {
  navy: '#001233',
  navyMid: '#001d4a',
  navyLight: '#0a2a5e',
  gold: '#b89a3e',
  goldBright: '#d4b254',
  goldPale: '#f0e0a8',
  white: '#ffffff',
  offWhite: '#f7f6f2',
  rule: '#ddd8cc',
  ruleDark: '#2a3f6a',
  body: '#2c2c2c',
  muted: '#6b7280',
  label: '#8a8a8a',
  positive: '#0a5c42',
  positiveBg: '#ecf7f2',
  negative: '#991b1b',
  negativeBg: '#fef2f2',
  amber: '#92400e',
  amberBg: '#fffbeb',
  blue: '#1e3a8a',
  blueBg: '#eff6ff',
};

export const FONTS = {
  serif: "'Playfair Display', Georgia, serif",
  sans: "'IBM Plex Sans', system-ui, sans-serif",
  mono: "'IBM Plex Mono', 'Courier New', monospace",
};

export const BREAKPOINTS = {
  desktop: 1024,
  tablet: 768,
  mobile: 480,
  small: 375,
};

// Manager profile data
export const MANAGER = {
  name: 'Adithyo Dewangga Wijaya',
  title: 'Algorithmic Strategy Developer · Singapore',
  avatar: 'https://avatars.githubusercontent.com/u/45558534?v=4',
  github: 'https://github.com/adithyodw',
  linkedin: 'https://sg.linkedin.com/in/adithyodewangga',
  mql5p: 'https://www.mql5.com/en/users/adithyodw',
  myfxbook: 'https://www.myfxbook.com/members/adithyodw',
  telegram: 'https://t.me/tol_langit',
  employer: 'Singtel',
  location: 'Singapore',
  activeSince: 'January 2021',
};

export const IC_MARKETS = 'https://icmarkets.com/?camp=49934';

// Strategy data — updated May 2026 (data as of 2 May 2026, live values from MyFXBook API)
export const BASE = [
  {
    id: 'v10',
    key: 'v10',
    ticker: 'TLV10',
    name: 'TOL LANGIT V10',
    short: 'V10',
    badge: 'LOW RISK',
    bClass: 'rp-low',
    mql5: 'https://www.mql5.com/en/signals/1083101',
    myfx: 'https://www.myfxbook.com/members/adithyodw/tol-langit-v10/8671765',
    ss: 'https://icmarkets.signalstart.com/analysis/tol-langit-v10/232541',
    zulu: 'https://www.zulutrade.com/trader/417743/trading',
    platform: 'MT4',
    gain: '+2,233.83%',
    win: '81.50%',
    pf: '1.96',
    mo: '+5.63%',
    ann: '~92% p.a. (4.8-yr CAGR)',
    ddBal: '10.18%',
    ddBalC: 'amber',
    ddEq: '67.92%',
    ddEqC: 'neg',
    trades: '4,519',
    wins: '3,683',
    losses: '836',
    days: '790',
    act: '46.33%',
    lot: '0.03',
    lotN: 'Conservative',
    dur: '~5 Years 3 Months',
    durS: '278 weeks · Inception Jan 2021',
    instr: '11 Forex Pairs',
    instrS: 'EUR/USD, GBP/USD, USD/JPY + 8 cross pairs',
    tpw: '0–1',
    lastT: '28 days ago',
    hold: '~1 Day',
    holdS: 'Multi-Day Swing / Positional',
    stype: 'Trend-Following Expert Advisor',
    snote: 'Smart Grid Recovery · Fully Automated · MT4',
    grid: 'Smart Grid Recovery',
    gridN: 'Max 5 orders/pair · 100-pip minimum spacing',
    gridT: 'amber',
    rorLvl: 'LOW',
    rorC: COLORS.positive,
    rorD: 'A 5+ year continuous live track record across four distinct market regimes (2021–2024) provides statistically robust evidence of strategy performance. Balance drawdown of 10.18% is consistent with a conservative mandate. Profit factor of 2.73 over 4,519 trades is statistically significant. Grid exposure is bounded and capped.',
    useCase: 'Core Capital Preservation',
    useCaseD:
      'Suitable as a core systematic allocation prioritising capital preservation with steady compounding. Structurally analogous to a conservative fixed-income systematic strategy within a diversified portfolio.',
    inv: 'Conservative · Long-Term',
    invN: 'Appropriate for investors with a multi-year time horizon and low drawdown tolerance. Suitable as a primary systematic allocation.',
    alloc:
      '5–20% portfolio allocation. Pair with higher-return strategies to optimise risk-adjusted returns.',
    volP: 'Low–Moderate',
    ddB: 'Contained balance drawdown with elevated floating equity exposure during grid recovery sequences.',
    corrN: 'Multi-pair diversification reduces single-currency concentration risk.',
    annRet: [
      { y: '2021', v: '+110.41%', n: 'Inception Year' },
      { y: '2022', v: '+63.02%', n: 'Volatile Cycle' },
      { y: '2023', v: '+39.16%', n: 'Steady Compounding' },
      { y: '2024', v: '+57.74%', n: 'Strong Recovery' },
    ],
  },
  {
    id: 'etfgold',
    key: 'etfgold',
    ticker: 'TLETFG',
    name: 'TOL LANGIT ETF GOLD',
    short: 'ETF Gold',
    badge: 'MEDIUM RISK',
    bClass: 'rp-med',
    mql5: 'https://www.mql5.com/en/signals/2360336',
    myfx: 'https://www.myfxbook.com/members/adithyodw/tol-langit-etf-gold/12042787',
    ss: 'https://icmarkets.signalstart.com/analysis/tol-langit-etf-gold/288423',
    platform: 'MT5',
    gain: '+206.02%',
    win: '78.93%',
    pf: '2.50',
    mo: '+60.67%',
    ann: '~206% in 3+ months (early stage — annualised CAGR unreliable)',
    ddBal: '42.06%',
    ddBalC: 'amber',
    ddEq: '30.1%',
    ddEqC: 'amber',
    trades: '356',
    wins: '281',
    losses: '75',
    days: '91',
    act: '21.69%',
    lot: '0.02',
    lotN: 'XAU/USD specialist',
    dur: '~3 Months',
    durS: '13 weeks · Inception Feb 2026',
    instr: 'XAU/USD + AUDCAD',
    instrS: 'XAUUSD (primary 292 deals) · AUDCAD (64 deals)',
    tpw: '~35',
    lastT: 'Active · May 2, 2026',
    hold: '~4 Hours',
    holdS: 'Near-Intraday Scalping',
    stype: 'AI-Verified XAU/USD Strategy',
    snote: 'Institutional Logic · No Grid · Gold Specialist · MT5',
    grid: 'None',
    gridN: 'Single-position model per signal — structurally clean',
    gridT: 'green',
    rorLvl: 'MODERATE — STRONG EARLY SIGNALS',
    rorC: COLORS.amber,
    rorD: 'A 13-week (3-month), 356-trade live track record delivering +207.3% total gain. Profit factor of 2.64 and 78.93% win rate across 356 trades are statistically compelling. April 2026 contributed +191.15% with May 2026 adding +3.03% (partial). Maximum balance drawdown of 39.17% is moderate for a gold-specialist strategy. Current drawdown is 30.1% — elevated from intra-period May volatility. Recovery factor of 5.74 is exceptional. Instrument breakdown: XAUUSD 292 trades (PF 2.45), AUDCAD 64 trades (PF 3.49). The 3-month milestone has been reached with strong statistical indicators. Full-cycle characterisation requires 6+ months of verified track record.',
    useCase: 'Gold Specialist Growth Satellite',
    useCaseD:
      'XAU/USD focused growth strategy delivering +207.3% in its first 3 months with no grid mechanics. Profit factor of 2.64 across 356 verified trades confirm a structurally sound risk profile. April 2026 (+191.15%) and May 2026 +3.03% (partial) demonstrate exceptional return generation potential. Current drawdown of 30.1% is elevated but structurally managed. The 3-month maturation milestone has been reached with compelling results — formal strategic allocation appropriate with disciplined position sizing.',
    inv: 'Growth-Oriented · Gold-Focused · 3-Month Milestone Reached',
    invN: 'Investors seeking systematic gold exposure with a verified 3-month track record. Growth-oriented investors may initiate formal allocation with disciplined position sizing. Current drawdown of 30.1% warrants close monitoring. Continue monthly statistical reviews. Full-cycle confidence requires 6-month milestone (August 2026).',
    alloc:
      '5–15% growth satellite appropriate for risk-tolerant investors. The 3-month milestone has been passed with strong results. Full statistical review recommended before increasing allocation beyond 15%.',
    volP: 'High (XAU/USD concentration)',
    ddB: 'Maximum balance drawdown of 39.17% is moderate for a gold-specialist strategy. Current drawdown is 30.1% as of May 2, 2026 — up from 8.69% on April 30, reflecting intra-period May volatility. No grid mechanics means drawdown is structurally contained. Equity exposure from near-intraday hold times is well-managed.',
    corrN:
      'XAU/USD-dominated exposure. Minimal correlation to V10 forex grid strategies. Moderate correlation with TOL LANGIT ETF — do not pair these as a diversification hedge for gold exposure.',
    annRet: [
      { y: '2026', v: '+207.3% YTD', n: 'Feb +24.87% · Mar −17.96% · Apr +191.15% · May +3.03%' },
    ],
  },
];
