// Design tokens exported as JavaScript objects for use in styled components
export const COLORS = {
  navy: '#001233',
  navyMid: '#001d4a',
  navyLight: '#0a2a5e',
  gold: '#b89a3e',
  goldBright: '#d4b254',
  goldPale: '#f0e0a8',
  white: '#ffffff',
  offWhite: '#f7f6f2',
  rule: '#ddd8cc',
  ruleDark: '#2a3f6a',
  body: '#2c2c2c',
  muted: '#6b7280',
  label: '#8a8a8a',
  positive: '#0a5c42',
  positiveBg: '#ecf7f2',
  negative: '#991b1b',
  negativeBg: '#fef2f2',
  amber: '#92400e',
  amberBg: '#fffbeb',
  blue: '#1e3a8a',
  blueBg: '#eff6ff',
};

export const FONTS = {
  serif: "'Playfair Display', Georgia, serif",
  sans: "'IBM Plex Sans', system-ui, sans-serif",
  mono: "'IBM Plex Mono', 'Courier New', monospace",
};

export const BREAKPOINTS = {
  desktop: 1024,
  tablet: 768,
  mobile: 480,
  small: 375,
};

// Manager profile data
export const MANAGER = {
  name: 'Adithyo Dewangga Wijaya',
  title: 'Algorithmic Strategy Developer · Singapore',
  avatar: 'https://avatars.githubusercontent.com/u/45558534?v=4',
  github: 'https://github.com/adithyodw',
  linkedin: 'https://sg.linkedin.com/in/adithyodewangga',
  mql5p: 'https://www.mql5.com/en/users/adithyodw',
  myfxbook: 'https://www.myfxbook.com/members/adithyodw',
  telegram: 'https://t.me/tol_langit',
  employer: 'Singtel',
  location: 'Singapore',
  activeSince: 'January 2021',
};

export const IC_MARKETS = 'https://icmarkets.com/?camp=49934';

// Strategy data — updated May 2026 (data as of 30 Apr 2026, MyFXBook verified)
export const BASE = [
  {
    id: 'v10',
    key: 'v10',
    ticker: 'TLV10',
    name: 'TOL LANGIT V10',
    short: 'V10',
    badge: 'LOW RISK',
    bClass: 'rp-low',
    mql5: 'https://www.mql5.com/en/signals/1083101',
    myfx: 'https://www.myfxbook.com/members/adithyodw/tol-langit-v10/8671765',
    ss: 'https://icmarkets.signalstart.com/analysis/tol-langit-v10/232541',
    zulu: 'https://www.zulutrade.com/trader/417743/trading',
    platform: 'MT4',
    gain: '+1,447.47%',
    win: '81.50%',
    pf: '2.73',
    mo: '+2.65%',
    ann: '~67.1% p.a. (5-yr CAGR)',
    ddBal: '10.18%',
    ddBalC: 'amber',
    ddEq: '72.94%',
    ddEqC: 'neg',
    trades: '4,519',
    wins: '3,683',
    losses: '836',
    days: '790',
    act: '46.33%',
    lot: '0.03',
    lotN: 'Conservative',
    dur: '~5 Years 3 Months',
    durS: '278 weeks · Inception Jan 2021',
    instr: '11 Forex Pairs',
    instrS: 'EUR/USD, GBP/USD, USD/JPY + 8 cross pairs',
    tpw: '0–1',
    lastT: '28 days ago',
    hold: '~1 Day',
    holdS: 'Multi-Day Swing / Positional',
    stype: 'Trend-Following Expert Advisor',
    snote: 'Smart Grid Recovery · Fully Automated · MT4',
    grid: 'Smart Grid Recovery',
    gridN: 'Max 5 orders/pair · 100-pip minimum spacing',
    gridT: 'amber',
    rorLvl: 'LOW',
    rorC: COLORS.positive,
    rorD: 'A 5+ year continuous live track record across four distinct market regimes (2021–2024) provides statistically robust evidence of strategy performance. Balance drawdown of 10.18% is consistent with a conservative mandate. Profit factor of 2.73 over 4,519 trades is statistically significant. Grid exposure is bounded and capped.',
    useCase: 'Core Capital Preservation',
    useCaseD:
      'Suitable as a core systematic allocation prioritising capital preservation with steady compounding. Structurally analogous to a conservative fixed-income systematic strategy within a diversified portfolio.',
    inv: 'Conservative · Long-Term',
    invN: 'Appropriate for investors with a multi-year time horizon and low drawdown tolerance. Suitable as a primary systematic allocation.',
    alloc:
      '5–20% portfolio allocation. Pair with higher-return strategies to optimise risk-adjusted returns.',
    volP: 'Low–Moderate',
    ddB: 'Contained balance drawdown with elevated floating equity exposure during grid recovery sequences.',
    corrN: 'Multi-pair diversification reduces single-currency concentration risk.',
    annRet: [
      { y: '2021', v: '+110.41%', n: 'Inception Year' },
      { y: '2022', v: '+63.02%', n: 'Volatile Cycle' },
      { y: '2023', v: '+39.16%', n: 'Steady Compounding' },
      { y: '2024', v: '+57.74%', n: 'Strong Recovery' },
    ],
  },
  {
    id: 'v10hr',
    key: 'v10hr',
    ticker: 'TLV10H',
    name: 'TOL LANGIT V10 HIGH RISK',
    short: 'V10 HR',
    badge: 'HIGH RISK',
    bClass: 'rp-hi',
    mql5: 'https://www.mql5.com/en/signals/2296225',
    myfx: 'https://www.myfxbook.com/members/adithyodw/tol-langit-v10-high-risk/11424740',
    ss: 'https://icmarkets.signalstart.com/analysis/tol-langit-high-risk/278500',
    platform: 'MT4',
    gain: '+957.48%',
    win: '93.84%',
    pf: '2.49',
    mo: '+14.31%',
    ann: '~173.58% p.a.',
    ddBal: '17.74%',
    ddBalC: 'neg',
    ddEq: '95.28%',
    ddEqC: 'neg',
    trades: '715',
    wins: '671',
    losses: '44',
    days: '173',
    act: '43.25%',
    lot: '0.11–0.20',
    lotN: 'Aggressive',
    dur: '~13 Months',
    durS: '57 weeks · Inception Mar 2025',
    instr: '11 Forex Pairs',
    instrS: 'EUR/USD, GBP/USD, USD/JPY + 8 cross pairs',
    tpw: '~1',
    lastT: '9 days ago',
    hold: '~2 Days',
    holdS: 'Multi-Day Swing / Positional',
    stype: 'Aggressive Trend Expert Advisor',
    snote: 'Grid Recovery Mode · High-Frequency Variation · MT4',
    grid: 'Smart Grid Recovery',
    gridN: '70–100 pip spacing · Aggressive lot scaling',
    gridT: 'amber',
    rorLvl: 'HIGH',
    rorC: COLORS.negative,
    rorD: 'Equity drawdown of 95.28% represents near-total floating exposure under adverse conditions. Aggressive lot sizing of 0.11–0.20 per $1,000 materially amplifies both return and ruin probability. The 13-month track record is insufficient to characterise full-cycle risk.',
    useCase: 'Aggressive Growth Satellite',
    useCaseD:
      'Appropriate only as a high-risk satellite for investors with sophisticated understanding of grid mechanics and explicit acceptance of deep drawdown scenarios. Not suitable as a primary allocation.',
    inv: 'Aggressive · High-Tolerance Sophisticated',
    invN: 'Experienced investors only. Capital allocated here must be explicitly designated for speculative deployment.',
    alloc: 'Maximum 5–10% of speculative capital. Not appropriate as a core allocation vehicle.',
    volP: 'Very High',
    ddB: 'Equity drawdown of 95.28% reflects extreme open-position exposure during recovery sequences.',
    corrN:
      'Identical instrument universe to V10 Low Risk. High correlation — do not combine as a diversification pair.',
  },
  {
    id: 'etf',
    key: 'etf',
    ticker: 'TLETF',
    name: 'TOL LANGIT ETF',
    short: 'ETF',
    badge: 'HIGH RISK',
    bClass: 'rp-hi',
    mql5: 'https://www.mql5.com/en/signals/2353105',
    myfx: 'https://www.myfxbook.com/members/adithyodw/tol-langit-etf/11891377',
    ss: 'https://icmarkets.signalstart.com/analysis/tol-langit-etf/285680',
    zulu: 'https://www.zulutrade.com/trader/430869/trading',
    platform: 'MT5',
    gain: '+10.62%',
    win: '80.00%',
    pf: '1.69',
    mo: '+107.79%',
    ann: 'Insufficient history for reliable CAGR',
    ddBal: '70.72%',
    ddBalC: 'neg',
    ddEq: '40.75%',
    ddEqC: 'neg',
    trades: '515',
    wins: '412',
    losses: '103',
    days: '120',
    act: '47.6%',
    lot: '0.02',
    lotN: 'XAU/USD-adjusted',
    dur: '~4 Months',
    durS: '17 weeks · Inception Jan 2026',
    instr: 'Forex + XAU/USD',
    instrS: 'XAUUSD (primary) · AUDCAD, GBPUSD, EURUSD, USDJPY + more',
    tpw: '~33',
    lastT: 'Active · Apr 30, 2026',
    hold: '~10 Hours',
    holdS: 'Near-Intraday to Multi-Day',
    stype: 'AI-Verified Hybrid Expert Advisor',
    snote: 'Bayesian Model · No Grid · Forex + Gold · MT5',
    grid: 'None',
    gridN: 'Single-position model per signal — structurally clean',
    gridT: 'green',
    rorLvl: 'HIGH — VOLATILE RECOVERY',
    rorC: COLORS.negative,
    rorD: 'A 4-month live track record (Jan–Apr 2026) demonstrating extreme volatility: +105.59% in January, +18.05% in February, a severe −78.06% drawdown in March, and a remarkable +107.79% recovery in April. Net gain of +10.62% reflects significant capital flows ($21.9k deposits, $18.9k withdrawals). Maximum balance drawdown of 70.72% remains materially elevated. Profit factor has improved to 1.69. Sharpe ratio of 0.10 indicates return is disproportionate to volatility risk. Recovery confirmed — continued active monitoring required.',
    useCase: 'High-Risk Gold-Forex Satellite',
    useCaseD:
      'Demonstrated volatile but recovering equity curve. The April 2026 recovery of +107.79% following a −78.06% March drawdown confirms the strategy\'s recovery mechanics. Profit factor improved to 1.69 over 4 months. Not suitable as a primary allocation until balance drawdown stabilises materially below 30%. The AI-verified hybrid model and absence of grid mechanics maintain structural advantage over grid-based strategies.',
    inv: 'Aggressive · High-Tolerance · Active Monitor',
    invN: 'Only for investors with explicit tolerance for deep drawdown. Drawdown recovery is underway but maximum balance drawdown of 70.72% remains elevated. Monitor monthly and reassess at the 6-month milestone.',
    alloc:
      'Maximum 5–10% speculative satellite. Monitor monthly. Reduce or exit if balance drawdown exceeds 85%.',
    volP: 'Very High (Gold-driven)',
    ddB: 'Maximum balance drawdown of 70.72% reflects severe March 2026 losses (−78.06% monthly). April 2026 recovery of +107.79% has restored equity to net positive territory overall. Equity drawdown of 40.75% remains elevated. Active monitoring required until balance drawdown stabilises below 30%.',
    corrN:
      'Low correlation to V10 forex strategies due to gold and MT5 exposure. Provides genuine diversification but currently impairs portfolio risk-adjusted returns.',
    annRet: [
      { y: '2026', v: '+10.62% YTD', n: 'Jan +105.59% · Feb +18.05% · Mar −78.06% · Apr +107.79%' },
    ],
  },
  {
    id: 'etfgold',
    key: 'etfgold',
    ticker: 'TLETFG',
    name: 'TOL LANGIT ETF GOLD MR',
    short: 'ETF Gold MR',
    badge: 'MEDIUM RISK',
    bClass: 'rp-med',
    mql5: 'https://www.mql5.com/en/signals/2360336',
    myfx: 'https://www.myfxbook.com/members/adithyodw/tol-langit-etf-mr/12023120',
    ss: null,
    platform: 'MT5',
    gain: '+197.33%',
    win: '78.57%',
    pf: '2.52',
    mo: '+190.23%',
    ann: '~197% in 3 months (early stage — annualised CAGR unreliable)',
    ddBal: '39.17%',
    ddBalC: 'amber',
    ddEq: '8.69%',
    ddEqC: 'green',
    trades: '350',
    wins: '275',
    losses: '75',
    days: '89',
    act: '21.69%',
    lot: '0.02',
    lotN: 'XAU/USD specialist',
    dur: '~3 Months',
    durS: '13 weeks · Inception Feb 2026',
    instr: 'XAU/USD + AUDCAD',
    instrS: 'XAUUSD (primary 286 deals) · AUDCAD (64 deals)',
    tpw: '~35',
    lastT: 'Active · Apr 30, 2026',
    hold: '~4 Hours',
    holdS: 'Near-Intraday Scalping',
    stype: 'AI-Verified XAU/USD Strategy',
    snote: 'Institutional Logic · No Grid · Gold Specialist · MT5',
    grid: 'None',
    gridN: 'Single-position model per signal — structurally clean',
    gridT: 'green',
    rorLvl: 'MODERATE — STRONG EARLY SIGNALS',
    rorC: COLORS.amber,
    rorD: 'A 13-week (3-month), 350-trade live track record delivering +197.33% total gain. Profit factor of 2.52 and 78.57% win rate across 350 trades are statistically compelling. April 2026 alone contributed +190.23% — exceptional return for a single month. Maximum balance drawdown of 39.17% is moderate for a gold-specialist strategy. Current drawdown is 8.69% — near equity peak. Recovery factor of 5.47 is exceptional. Instrument breakdown: XAUUSD 286 trades (PF 2.38), AUDCAD 64 trades (PF 3.49). The 3-month milestone has been reached with strong statistical indicators. Full-cycle characterisation requires 6+ months of verified track record.',
    useCase: 'Gold Specialist Growth Satellite',
    useCaseD:
      'XAU/USD focused growth strategy delivering +197.33% in its first 3 months with no grid mechanics. Profit factor of 2.52 across 350 verified trades and a current drawdown of only 8.69% confirm a structurally sound risk profile. April 2026 (+190.23%) demonstrates exceptional return generation potential. The 3-month maturation milestone has been reached with compelling results — formal strategic allocation appropriate with disciplined position sizing.',
    inv: 'Growth-Oriented · Gold-Focused · 3-Month Milestone Reached',
    invN: 'Investors seeking systematic gold exposure with a verified 3-month track record. Growth-oriented investors may initiate formal allocation with disciplined position sizing. Continue monthly statistical reviews. Full-cycle confidence requires 6-month milestone.',
    alloc:
      '5–15% growth satellite appropriate for risk-tolerant investors. The 3-month milestone has been passed with strong results. Full statistical review recommended before increasing allocation beyond 15%.',
    volP: 'High (XAU/USD concentration)',
    ddB: 'Maximum balance drawdown of 39.17% is moderate for a gold-specialist strategy. Current drawdown is 8.69% — the account is near its equity peak as of April 30, 2026. No grid mechanics means drawdown is structurally contained. Equity exposure from near-intraday hold times is well-managed.',
    corrN:
      'XAU/USD-dominated exposure. Minimal correlation to V10 forex grid strategies. Moderate correlation with TOL LANGIT ETF — do not pair these as a diversification hedge for gold exposure.',
    annRet: [
      { y: '2026', v: '+197.33% YTD', n: 'Feb +24.87% · Mar −17.96% · Apr +190.23%' },
    ],
  },
];
